export const PLAYERS_DATA_BASE = [
	{ id: 1, name: "Antonio", score: 85 },
	{ id: 2, name: "Beatriz", score: 73 },
	{ id: 3, name: "Carmen", score: 66 },
	{ id: 4, name: "David", score: 91 },
	{ id: 5, name: "Elena", score: 78 },
	{ id: 6, name: "Francisco", score: 59 },
	{ id: 7, name: "Gabriela", score: 88 },
	{ id: 8, name: "Hugo", score: 62 },
	{ id: 9, name: "Isabel", score: 97 },
	{ id: 10, name: "Javier", score: 90 },
	// { id: 11, name: "Laura", score: 71 },
	// { id: 12, name: "Manuel", score: 81 },
	// { id: 13, name: "Natalia", score: 76 },
	// { id: 14, name: "Oscar", score: 83 },
	// { id: 15, name: "Paula", score: 67 },
	// { id: 16, name: "Quim", score: 69 },
	// { id: 17, name: "Rocío", score: 94 },
	// { id: 18, name: "Sergio", score: 74 },
	// { id: 19, name: "Tamara", score: 87 },
	// { id: 20, name: "Uriel", score: 63 },
	// { id: 21, name: "Valeria", score: 91 },
	// { id: 22, name: "Walter", score: 70 },
	// { id: 23, name: "Ximena", score: 84 },
	// { id: 24, name: "Yago", score: 56 },
	// { id: 25, name: "Zulema", score: 77 },
	// { id: 26, name: "Andrés", score: 88 },
	// { id: 27, name: "Blanca", score: 60 },
	// { id: 28, name: "Carlos", score: 92 },
	// { id: 29, name: "Daniela", score: 69 },
	// { id: 30, name: "Esteban", score: 80 },
	// { id: 31, name: "Fabiola", score: 72 },
	// { id: 32, name: "Guillermo", score: 68 },
	// { id: 33, name: "Helena", score: 95 },
	// { id: 34, name: "Iván", score: 53 },
	// { id: 35, name: "Joaquín", score: 87 },
	// { id: 36, name: "Karina", score: 66 },
	// { id: 37, name: "Luis", score: 82 },
	// { id: 38, name: "Marta", score: 90 },
	// { id: 39, name: "Nicolás", score: 76 },
	// { id: 40, name: "Olga", score: 61 },
	// { id: 41, name: "Pedro", score: 79 },
	// { id: 42, name: "Queralt", score: 55 },
	// { id: 43, name: "Raúl", score: 73 },
	// { id: 44, name: "Salvador", score: 85 },
	// { id: 45, name: "Teresa", score: 67 },
	// { id: 46, name: "Ulises", score: 83 },
	// { id: 47, name: "Virginia", score: 71 },
	// { id: 48, name: "Xavier", score: 93 },
	// { id: 49, name: "Yolanda", score: 74 },
	// { id: 50, name: "Zoe", score: 86 },
	// { id: 51, name: "Alba", score: 80 },
	// { id: 52, name: "Bruno", score: 68 },
	// { id: 53, name: "Cecilia", score: 91 },
	// { id: 54, name: "Diana", score: 75 },
	// { id: 55, name: "Eva", score: 88 },
	// { id: 56, name: "Fernando", score: 66 },
	// { id: 57, name: "Gonzalo", score: 85 },
	// { id: 58, name: "Héctor", score: 79 },
	// { id: 59, name: "Irene", score: 73 },
	// { id: 60, name: "José", score: 90 },
	// { id: 61, name: "Karla", score: 69 },
	// { id: 62, name: "Luisana", score: 82 },
	// { id: 63, name: "Manuela", score: 65 },
	// { id: 64, name: "Nerea", score: 93 },
	// { id: 65, name: "Octavio", score: 77 },
	// { id: 66, name: "Patricia", score: 86 },
	// { id: 67, name: "Quique", score: 58 },
	// { id: 68, name: "Rafael", score: 84 },
	// { id: 69, name: "Sandra", score: 76 },
	// { id: 70, name: "Tomás", score: 64 },
	// { id: 71, name: "Ursula", score: 87 },
	// { id: 72, name: "Vera", score: 71 },
	// { id: 73, name: "Wendy", score: 88 },
	// { id: 74, name: "Ximena", score: 67 },
	// { id: 75, name: "Yannick", score: 83 },
	// { id: 76, name: "Zulema", score: 72 },
	// { id: 77, name: "Alicia", score: 70 },
	// { id: 78, name: "Benjamín", score: 89 },
	// { id: 79, name: "Claudia", score: 93 },
	// { id: 80, name: "David", score: 60 },
	// { id: 81, name: "Estefanía", score: 86 },
	// { id: 82, name: "Fernando", score: 55 },
	// { id: 83, name: "Guadalupe", score: 79 },
	// { id: 84, name: "Héctor", score: 92 },
	// { id: 85, name: "Ignacio", score: 71 },
	// { id: 86, name: "Juan", score: 75 },
	// { id: 87, name: "Katherine", score: 66 },
	// { id: 88, name: "Luis", score: 90 },
	// { id: 89, name: "María", score: 94 },
	// { id: 90, name: "Nicolás", score: 65 },
	// { id: 91, name: "Oscar", score: 80 },
	// { id: 92, name: "Pablo", score: 78 },
	// { id: 93, name: "Quinta", score: 61 },
	// { id: 94, name: "Rosa", score: 85 },
	// { id: 95, name: "Simón", score: 68 },
	// { id: 96, name: "Tania", score: 72 },
	// { id: 97, name: "Ubaldo", score: 87 },
	// { id: 98, name: "Vera", score: 74 },
	// { id: 99, name: "Wilfredo", score: 81 },
	// { id: 100, name: "Ximena", score: 92 },
];
